Implement beregning for vilkårv2
navikt/su-se-framover pull request #233
Opened 2020-09-14 13:58 UTC by aryani1

Note: Lagat en ny sida för den 'nya' beregnings-sidan, har därför exporterat och återanvänt en del komponenter från den första beregnings-sidan.

Co-authored-by: ramziabuqassim <ramzi.abu.qassim@nav.no>
Co-authored-by: Ingar Almklov <ingara@gmail.com>

2020-09-14 14:14 UTC, RamziAbuQassim approved these changes

2020-09-15 07:52 UTC, ingara requested changes

2020-09-15 07:52 UTC, ingara commented on src/pages/saksoversikt/beregning/VisBeregning.tsx
> +                        );
Vi kan gjøre denne litt mer funksjonell og fin:

```suggestion
                        pipe(
                        	combineOptions(Arr.head(gruppe), Arr.last(gruppe)),
                        	Option.fold(
                        		() => null,
                        		([head, last]) => (
	                        		<tr key={beregning.id}>
	                                <td>{`${intl.formatDate(head.value.fom)} - ${intl.formatDate(last.value.tom)}`}</td>
	                                <td>{head.value.beløp}</td>
	                                <td>{head.value.grunnbeløp}</td>
	                            </tr>
                        		)
                        	)
                        );
```

der `combineOptions` defineres slik i `lib/fp.ts`:
```ts
import * as Apply from 'fp-ts/es6/Apply';
import * as Option from 'fp-ts/es6/Option';

export const combineOptions = Apply.sequenceT(Option.option);
```

2020-09-15 07:52 UTC, ingara commented on src/pages/saksoversikt/vilkår/Beregning.tsx
> +import messages from '../../saksoversikt/beregning/beregning-nb';
Som kommentert tidligere: hvis filer/koder skal deles mellom pages bør de ligge en samlet plass.

2020-09-15 07:52 UTC, ingara commented on src/pages/saksoversikt/vilkår/Beregning.tsx
> +                            >
Hvis denne knappen skal kjøre beregning men ikke submitte formet kan vi gjøre sånn:
```suggestion
                            <Knapp
                            	htmlType="button"
                                onClick={() => {
                                    startBeregning();
                                }}
                            >
```

2020-09-15 07:52 UTC, ingara commented on src/pages/saksoversikt/vilkår/Uførhet.tsx
>                          },
Skal dette være slik?

2020-09-15 11:56 UTC, ingara approved these changes

2020-09-15 12:04 UTC, merged