Legg til lagreknapp på revurderingsflyten
navikt/su-se-framover pull request #695
Opened 2021-03-24 14:30 UTC by richardmartinsen

2021-03-25 07:42 UTC, ingara requested changes
En ting jeg savner over hele fjøla her er feilhåndtering. Vi bør vise varsel til brukeren om noen av API-kallene feiler.

2021-03-25 07:42 UTC, ingara commented on src/pages/saksbehandling/revurdering/bunnknapper/RevurderingBunnknapper.tsx
> +    onNesteClick?(): void;
Vi kan kanskje gjøre nesteknappgreiene litt tydeligere for konsumentn hvis vi endrer til 

```suggestion
    onNesteClick: "submit" | () => void;
```

og så endrer knappkoden til

```ts
                <Hovedknapp
                    spinner={props.onNesteClickSpinner}
                    onClick={props.onNesteClick === "submit" ? undefined : props.onNesteClick}
                    htmlType={props.onNesteClick === "submit" ? 'submit' : 'button'}
                >
```

2021-03-25 07:42 UTC, ingara commented on src/pages/saksbehandling/revurdering/bunnknapper/RevurderingBunnknapper.tsx
> +                    spinner={props.onLagreOgFortsettSenereClickSpinner ?? undefined}
Er vel unødvendig med `?? undefined` her?

2021-03-25 07:42 UTC, ingara commented on src/pages/saksbehandling/revurdering/bunnknapper/RevurderingBunnknapper.tsx
> +    onTilbakeClick(): void;
Det ser ut til at i alle tilfellene så gjøres det en `history.push` i disse callbackene. Da bør vi heller ta inn en streng og bruke ei lenke i stedet for en knapp.

2021-03-25 07:42 UTC, ingara commented on src/pages/saksbehandling/revurdering/oppsummering/RevurderingsOppsummering.tsx
> +                    }
Ser for meg ut som at dette kan byttes ut med 
```suggestion
                    onNesteClickSpinner={RemoteData.isPending(sendtTilAttesteringStatus}
```

og at hele `SubmittedStatus`-enumen kan fjernes.

2021-03-25 07:42 UTC, ingara commented on src/pages/saksbehandling/revurdering/revurderingIntro/RevurderingIntroForm.tsx
> +                    }}
Jeg tror vi kan fjerne hele `SubmittedStatus`-greiene og heller la neste-knappen submitte formet (og gjøre `props.onNesteClick(values.fraOgMed, values.årsak, values.begrunnelse);` der) og sende inn `props.onLagreOgFortsettSenereClick(formik.values.fraOgMed, formik.values.årsak, formik.values.begrunnelse);` til `onLagreOgFortsettSenereClick` her.

2021-03-25 07:42 UTC, ingara commented on src/pages/saksbehandling/revurdering/endringAvFradrag/EndringAvFradrag.tsx
>      );
Jeg syns denne filen var litt fram-og-tilbake-og-her-og-der. Forslag;

- La `beregnOgSimulerRevurdering` returnere responsen sin
- Fjern hele `SubmittedStatus`
- La `onSubmit` kalle `beregnOgSimulerRevurdering`, sjekke om responsen var suksess og gjøre navigeringa
- Lag `handleLagreOgFortsettSenereClick`; denne kaller `beregnOgSimulerRevurdering`, sjekker om responsen var suksess og gjør navigering

2021-03-25 12:13 UTC, hestad commented on src/pages/saksbehandling/revurdering/revurderingIntro/RevurderingIntroForm.tsx
> +                    }}
submittedStatus ble beholdt noen steder med tanke på å differensiere spinnere.

2021-03-26 06:29 UTC, ingara approved these changes

2021-03-26 08:05 UTC, merged